/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getPriceLabel(String item, Double price) {
        String output = String.format("The price for item: %s is %.2f", item, price);
        return output;
    }

    public static void main(String[] args) {
        
    }
}
